/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaotian_demo_test_native__HelloWorld */

#ifndef _Included_com_xiaotian_demo_test_native__HelloWorld
#define _Included_com_xiaotian_demo_test_native__HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaotian_demo_test_native__HelloWorld
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaotian_demo_test_native_1_HelloWorld_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
