server:
  port: 8888
  address: 127.0.0.1

spring:
  boot:
    admin:
      client:
        url: "http://www.sunfeilong.cn:8888"
        instance:
          name: "SpringAdminClient"


management:
  endpoints:
    web:
      exposure:
        include: "*"