server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '000000'
