server:
  port: 8080

spring:
  datasource:
    name: tidb
    url: jdbc:mysql://192.168.0.201:4000/test?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver