server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    hikari:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/mybatis?useSSL=false&useUnicode=true&autoReconnect=true&allowMultiQueries=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: '000000'
      maximum-pool-size: 100